name: Build and Publish

on:
  workflow_run:
    workflows: ["Run Tests"]
    types: [completed]

jobs:

  build:
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup python version
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install build tool
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          rm -rf dist/ build/ *.egg-info/
          python -m build

      - name: Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifacts
          path: dist/

  publish:
    needs: build
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Twine
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Download artifacts from build
        uses: actions/download-artifact@v4
        with:
          name: dist-artifacts
          path: dist/

      - name: Publish package
        run: |
          python -m twine upload --repository-url https://test.pypi.org/legacy/ dist/* --verbose
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
