name: Run Tests

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests
        run: |
          python -m pytest

      - name: Lint
        run: |
          python -m flake8 src tests --max-line-length=100 --ignore=E501,E203,E741

      - name: Check formatting
        run: |
          python -m black --check src tests
